### ISSUE TITLE
bug in gulpfile.js

### ISSUE THREAD

**Issue by siberianbear** [frontcraft/fronthack-repo#48]
In gulpfile.js at the end of task 'mustache' need to add a line:
".pipe(livereload())"

Right now there is no auto-refresh/reload of *.html-files in "html-preview" folder, because of the bug.

**Comment by bandanaman** [comment]
@siberianbear thanks for the point. Yes, currently only css autorefreshing works. I tried adding this line to mustache task as you descibed and it does the job for html in fact, but breaks the refreshing of css. 

https://github.com/vohof/gulp-livereload

**Comment by siberianbear** [comment]
Sorry, I'm not too experienced user of gulp yet.
Actually css-refreshing are works, but only together with refreshing html (that's why I've not seen that effect). So yes, my "patch" is not too good and need to search more correct one. Thanks for catch!

**Comment by frontcraft** [comment]
Maybe this snippet will be usefull http://stackoverflow.com/a/18991116
